withSpace/my-application.log, withSpace/src/main/java/hansung/cse/withSpace/controller/ScheduleController.java
* (GET /schedule/:scheduleId)
배열로 반환되는 형식에서 단건 조회로 수정
=> 스케줄 컨트롤러 반환 형태 수정

withSpace/.gitignore, withSpace/build.gradle, withSpace/src/main/java/hansung/cse/withSpace/config/auth/MyMemberDetailService.java, withSpace/src/main/java/hansung/cse/withSpace/config/auth/SecurityConfig.java, withSpace/src/main/java/hansung/cse/withSpace/controller/MemberController.java, withSpace/src/main/java/hansung/cse/withSpace/controller/WebController.java, withSpace/src/main/java/hansung/cse/withSpace/domain/Member.java, withSpace/src/main/java/hansung/cse/withSpace/repository/MemberRepository.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/member/MemberJoinRequestDto.java, withSpace/src/main/java/hansung/cse/withSpace/service/MemberService.java, withSpace/src/main/resources/application.yml, withSpace/src/main/resources/templates/home.html, withSpace/src/main/resources/templates/login.html, withSpace/src/main/resources/templates/main.html, withSpace/src/main/resources/templates/signup.html
- 이메일에 대한 unique 제약조건 추가
- 확인, 검증을 위해 간단한 html 파일 추가 (gpt의 도움을 받았음)
- 회원가입 로직 추가 - 비밀번호 암호화 
- 로그인 검증 기능 추가 
- 로그인 전에는 허용한 url에만 접근할 수 있게함(홈페이지, 로그인 페이지, 회원가입 페이지 + 회원가입 api)
- 로그아웃시 다시 허용된 url에만 접근 가능
- 간단하게 로그인시 메인 페이지로 이동 - 로그인 되어있는 회원의 이메일과 이름이 보이게함. 
- 이에 필요한 로그아웃, 로그인된 회원 조회 api 추가
=> spring security를 사용한 회원가입, 비밀번호 암호화, 로그인 검증

withSpace/src/test/resources/application.yml
=> test 폴더 application.yml 추가

withSpace/src/main/resources/application.yml
=> application.yml db 포트 수정

withSpace/build.gradle
=> build.gradle 파일 수정

withSpace/.gitignore, withSpace/build.gradle, withSpace/my-application.log, withSpace/src/main/resources/application-real.properties, withSpace/src/main/resources/application.yml
* build.gradle에 org.springframework.session:spring-session-jdbc 설정추가
=> build.gradle에 org.springframework.session:spring-session-jdbc 설정추가

withSpace/src/main/resources/application.properties
* application.properties 설정 추가
=> application.properties 설정 추가

withSpace/appspec.yml, withSpace/my-application.log
=> appspec.yml 추가

.idea/dbnavigator.xml, .idea/modules.xml, .idea/vcs.xml, .idea/withSpace-server.iml, scripts/deploy.sh
=> deploy.sh 추가

appspec.yml
=> appspec.yml 설정 추가

withSpace/src/main/java/hansung/cse/withSpace/config/WebConfig.java
=> CORS 해결하기 위한 WebConfig 추가

.idea/.gitignore
=> .idea/gitignore 추가

withSpace/src/main/java/hansung/cse/withSpace/controller/ProfileController.java, withSpace/src/main/resources/application-real1.properties, withSpace/src/main/resources/application-real2.properties
* 무중다 배포 위한 ProfileController추가
=> 무중다 배포 위한 ProfileController추가

.idea/dbnavigator.xml, .idea/vcs.xml, .idea/workspace.xml, appspec.yml, scripts/health.sh, scripts/profile.sh, scripts/start.sh, scripts/stop.sh, scripts/switch.sh
=> 무중단 배포 스크립트 추가

.idea/workspace.xml, scripts/start.sh
=> start.sh 파일 수정

.idea/workspace.xml, scripts/start.sh, withSpace/src/main/resources/application.properties
=> start.sh 수정

.idea/workspace.xml, scripts/start.sh
=> start.sh 경로 수정

.idea/workspace.xml, appspec.yml
=> health.sh timeout 수정

withSpace/src/main/java/hansung/cse/withSpace/TestDB.java, withSpace/src/main/java/hansung/cse/withSpace/domain/Member.java, withSpace/src/main/java/hansung/cse/withSpace/service/MemberService.java
회원 단건 조회 -> 
{
"count": 1,
"message": "회원 조회 성공",
"data": {
"id": 1,
"email": "change Email",
"memberName": "changeMemberName",
"createdAt": "2023-03-27T22:32:54.608038",
"updatedAt": "2023-03-27T22:33:29.988809",
"status": null,
"teamCount": 2,
"teamList": [
{
"teamId": 1,
"memberCount": 3,
"teamName": "D(member1)가 만든 팀 1",
"memberTeamList": [
{
"userId": 1,
"memberName": "changeMemberName",
"status": false
},
{
"userId": 2,
"memberName": "memberA : D의 팀원+D의 친구",
"status": false
},
{
"userId": 3,
"memberName": "memberB : D의 팀원+D의 친구",
"status": false
}
]
},
{
"teamId": 2,
"memberCount": 2,
"teamName": "D(member1)가 만든 팀 2",
"memberTeamList": [
{
"userId": 1,
"memberName": "changeMemberName",
"status": false
},
{
"userId": 4,
"memberName": "memberC : D의 팀원",
"status": false
}
]
}
], …
=> - 데이터 추가, 회원 createAt, updatedAt에 대한 로직 추가

withSpace/src/main/java/hansung/cse/withSpace/config/auth/SecurityConfig.java, withSpace/src/main/java/hansung/cse/withSpace/controller/FriendShipController.java, withSpace/src/main/java/hansung/cse/withSpace/controller/ScheduleController.java, withSpace/src/main/java/hansung/cse/withSpace/exception/friend/FriendAddException.java, withSpace/src/main/java/hansung/cse/withSpace/exception/handler/FriendExceptionHandler.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/friendship/FriendRequestDto.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/schedule/category/CategoryRequestDto.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/schedule/todo/ToDoDescriptionUpdateDto.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/schedule/todo/ToDoRequestDto.java, withSpace/src/main/java/hansung/cse/withSpace/service/FriendShipService.java, withSpace/src/main/java/hansung/cse/withSpace/service/ToDoService.java
* 스케줄, 카테고리, 투두 오류처리는 본인꺼 외에 다른사람꺼 작업 못하게 하는거여서 @PreAuthorize로 접근 거부 메세지와 함께 응답해주는거로 작성함
* 친구신청은 본인외에꺼 친구신청못하게 막는거랑 이미 친구인 사람한테 친구신청 보냈을 때 오류 발생하는거로 작성
1. memberId 1인 회원이 memberId2번의 스케줄에 카테고리를 추가하는 경우
2. memberId 1인 회원이 memberId2번의 스케줄에 카테고리(categoryId=3)를 수정하는 경우
3. memberId 1인 회원이 memberId2번의 스케줄에 카테고리(categoryId=3)를 삭제하는 경우
4.  memberId 1인 회원이 memberId2번의 스케줄에 카테고리(categoryId=3)에 todo를 추가할 경우
5. memberId 1인 회원이 memberId2번의 스케줄에 카테고리 todo(todoId=4)를 수정할 경우
6. memberId 1인 회원이 memberId2번의 스케줄에 카테고리 todo(todoId=4)를 삭제할 경우
7. 이미 친구 관계인 회원한테 친구신청을 보낸 경우
=> 스케줄, 카테고리, 투두, 친구신청 오류 처리

withSpace/src/main/java/hansung/cse/withSpace/config/auth/CustomSecurityUtil.java, withSpace/src/main/java/hansung/cse/withSpace/controller/PageController.java, withSpace/src/main/java/hansung/cse/withSpace/controller/RoomController.java, withSpace/src/main/java/hansung/cse/withSpace/domain/chat/Room.java, withSpace/src/main/java/hansung/cse/withSpace/domain/space/Block.java, withSpace/src/main/java/hansung/cse/withSpace/domain/space/Page.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/space/page/PageUpdateContentRequestDto.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/space/page/PageUpdateTitleRequestDto.java, withSpace/src/main/java/hansung/cse/withSpace/responsedto/space/page/PageDetailDto.java, withSpace/src/main/java/hansung/cse/withSpace/responsedto/space/page/block/BlockDto.java, withSpace/src/main/java/hansung/cse/withSpace/service/PageService.java, withSpace/src/main/java/hansung/cse/withSpace/service/RoomService.java
- 페이지 내용 업데이트
- 페이지 제목 업데이트
- 채팅방 제거기능 추가
=> 블럭기능 제거 + 페이지 content 관련 기능 추가 

withSpace/src/main/java/hansung/cse/withSpace/filter/CorsFilter.java
=> CORS 설정 수정

withSpace/build.gradle, withSpace/src/main/java/hansung/cse/withSpace/config/s3/AwsConfig.java, withSpace/src/main/java/hansung/cse/withSpace/controller/FileController.java, withSpace/src/main/resources/application.yml
이미지 저장 기능 추가 & 이미지 저장 관련 application.yml 파일 수정
=> 이미지 저장 기능 추가 & 이미지 저장 관련 application.yml 파일 수정

withSpace/src/main/java/hansung/cse/withSpace/controller/PageController.java, withSpace/src/main/java/hansung/cse/withSpace/repository/PageRepository.java, withSpace/src/main/java/hansung/cse/withSpace/responsedto/space/page/PageHierarchyDto.java, withSpace/src/main/java/hansung/cse/withSpace/service/PageService.java
=> 페이지 계층구조 조회기능 추가

withSpace/src/main/java/hansung/cse/withSpace/config/auth/CustomSecurityUtil.java, withSpace/src/main/java/hansung/cse/withSpace/controller/PageController.java, withSpace/src/main/java/hansung/cse/withSpace/controller/SpaceController.java, withSpace/src/main/java/hansung/cse/withSpace/domain/Member.java, withSpace/src/main/java/hansung/cse/withSpace/domain/space/Page.java, withSpace/src/main/java/hansung/cse/withSpace/domain/space/Space.java, withSpace/src/main/java/hansung/cse/withSpace/domain/space/TrashCan.java, withSpace/src/main/java/hansung/cse/withSpace/exception/TrashCan/TrashCanNotFoundException.java, withSpace/src/main/java/hansung/cse/withSpace/exception/handler/PageExceptionHandler.java, withSpace/src/main/java/hansung/cse/withSpace/exception/handler/TrashCanExceptionHandler.java, withSpace/src/main/java/hansung/cse/withSpace/exception/page/PageNotInSpaceException.java, withSpace/src/main/java/hansung/cse/withSpace/exception/page/PageRestoreNotCurrentPageIdException.java, withSpace/src/main/java/hansung/cse/withSpace/repository/TrashCanRepository.java, withSpace/src/main/java/hansung/cse/withSpace/requestdto/space/page/PageRestoreRequestDto.java, withSpace/src/main/java/hansung/cse/withSpace/responsedto/space/page/PageDto.java, withSpace/src/main/java/hansung/cse/withSpace/responsedto/space/page/PageTrashCanDto.java, withSpace/src/main/java/hansung/cse/withSpace/service/MemberService.java, withSpace/src/main/java/hansung/cse/withSpace/service/PageService.java, withSpace/src/main/java/hansung/cse/withSpace/service/SpaceService.java, withSpace/src/main/java/hansung/cse/withSpace/service/TrashCanService.java
쓰레기통 TrashCan 엔티티 추가, 스페이스당 하나, 페이지와는 일대다관계  
- 페이지를 쓰레기통으로 옮기는 기능  
- 쓰레기통 조회
- 쓰레기통에 있는 페이지 복구 기능 
- 페이지 완전 삭제 기능
=> 페이지 쓰레기통 추가 

.idea/workspace.xml, appspec.yml, withSpace/src/main/java/hansung/cse/withSpace/TestDB.java
=> TestDB 주석 처리

withSpace/src/main/java/hansung/cse/withSpace/TestDB.java
=> TestDB 어노테이션 제거

withSpace/.gitignore, withSpace/src/main/java/hansung/cse/withSpace/controller/FriendShipController.java, withSpace/src/main/java/hansung/cse/withSpace/service/FriendShipService.java
=> 친구신청 검증 로직 수정

withSpace/.gitignore
=> application.yml 추가

withSpace/src/main/java/hansung/cse/withSpace/config/jwt/JwtAuthenticationFilter.java, withSpace/src/main/java/hansung/cse/withSpace/controller/FriendShipController.java, withSpace/src/main/java/hansung/cse/withSpace/responsedto/member/GetMemberResponseDto.java
접근권한 수정 / 로그인중인 회원조회 spaceId추가
=> 접근권한 수정 / 로그인중인 회원조회 spaceId추가

withSpace/src/main/java/hansung/cse/withSpace/controller/FriendShipController.java, withSpace/src/main/java/hansung/cse/withSpace/repository/FriendShipRepository.java, withSpace/src/main/java/hansung/cse/withSpace/service/FriendShipService.java
=> 친구요청수신목록 controller 추가

withSpace/src/main/java/hansung/cse/withSpace/controller/FriendShipController.java, withSpace/src/main/java/hansung/cse/withSpace/service/FriendShipService.java
1번 member가 4번 member에게 친구신청보낸 결과
4번이 1번한테 거절을 한 결과(테이블에 있는 친구신청목록을 삭제)
=> 친구 신청 거절 controller 추가

withSpace/src/main/java/hansung/cse/withSpace/config/websocket/HttpHandshakeInterceptor.java
beforeHandshake에서 request헤더 확인 위한 코드 추가
=> beforeHandshake에서 request헤더 확인 위한 코드 추가

withSpace/src/main/java/hansung/cse/withSpace/filter/CorsFilter.java
=> 프론트 배포 cors 설정

withSpace/src/main/java/hansung/cse/withSpace/filter/CorsFilter.java
=> 프론트 배포 cors 수정

withSpace/src/main/java/hansung/cse/withSpace/filter/CorsFilter.java
=> cors 헤더 설정 수정

withSpace/src/main/java/hansung/cse/withSpace/WithSpaceApplication.java
=> @EnableScheduling 주석처리
